name: Build and Push to ACR
on:
    # Allow to be called from other workflows.
    workflow_call:
    workflow_dispatch:
      inputs:
        deployment_run_id:
          description: 'The run ID of the deployment workflow.'
          required: true
          type: number

permissions:
    id-token: write
    contents: read

jobs:
    build_image:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@main

        - name: Azure authentication
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Setup .NET
          uses: actions/setup-dotnet@v2
          with:
              dotnet-version: '9.0.x'

        - name: Download environment variables
          uses: actions/download-artifact@v4
          with:
            name: env-vars-json
            github-token: ${{ github.token }}
            run-id: ${{ inputs.deployment_run_id || github.run_id}}

        - name: JSON to variables
          uses: antifree/json-to-variables@v1.2.0
          with:
            filename: env-vars.json
            prefix: INFRA

        - name: Show output
          run: |
            echo $INFRA_ACR_NAME
            echo $INFRA_RESOURCE_GROUP_NAME
            echo $INFRA_MANAGED_ENVIRONMENT_NAME
            
        - name: Login to Azure Container Registry
          run: |
             az acr login --name ${{ vars.INFRA_ACR_NAME }}
        
        #  Service Bus Worker
        - name: Build Docker image for ServiceBusWorker
          run: dotnet publish --os linux --arch x64 /t:PublishContainer -p ContainerImageTag="${{ github.sha }}"
          working-directory: src/ServiceBusWorker

        - name: Create alias for the ServiceBusWorker
          run: |
            docker tag servicebusworker:${{ github.sha }} ${{ vars.INFRA_ACR_NAME }}.azurecr.io/service-bus-worker:${{ github.sha }}

        - name: Push ServiceBusWorker image to Azure Container Registry
          run: |
            docker push ${{ vars.INFRA_ACR_NAME }}.azurecr.io/service-bus-worker:${{ github.sha }}


        #  Web App
        - name: Build Docker image for Web App
          run: dotnet publish --os linux --arch x64 /t:PublishContainer -p ContainerImageTag="${{ github.sha }}"
          working-directory: src/WebApplication1
        
        - name: Create alias for the Web App
          run: |
            docker tag webapplication1:${{ github.sha }} ${{ vars.INFRA_ACR_NAME }}.azurecr.io/web-app:${{ github.sha }}

        - name: Push Web App image to Azure Container Registry
          run: |
            docker push ${{ vars.INFRA_ACR_NAME }}.azurecr.io/web-app:${{ github.sha }}
