name: CD

on:
    workflow_dispatch:
    push:
        # branches:
            # - main
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@main

        - name: Azure authentication
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Setup .NET
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: '9.0.x'
        
        - name: Build and publish ServiceBusWorker
          run: dotnet publish -c Release -o out
          working-directory: src/ServiceBusWorker

        - name: Build Docker image for ServiceBusWorker
          run: dotnet publish --os linux --arch x64 /t:PublishContainer
          working-directory: src/ServiceBusWorker

        #  Log into existing Azure Container Registry
        - name: Log into Azure Container Registry
          uses: azure/docker-login@v1
          with:
            login-server: ${{ vars.ACR_NAME }}.azurecr.io
            # username: ${{ secrets.ACR_USERNAME }}
            # password: ${{ secrets.ACR_PASSWORD }}
        
        #  Create alias for the image
        - name: Create alias for the ServiceBusWorker
          run: |
            docker tag service-bus-worker ${{ vars.ACR_NAME }}.azurecr.io/service-bus-worker:${{ github.sha }}

        #  Push to ACR

        # - name: Push Docker image to Docker Hub
        #   env:
        #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        #   run: |
        #     echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        #     docker tag myapp:latest $DOCKER_USERNAME/myapp:latest
        #     docker push $DOCKER_USERNAME/myapp:latest