name: Continuous Integration

on:
  # Allow triggering manually.  
  workflow_dispatch:
  
  # Allow to be called from other workflows.
  workflow_call:
  
  # On any PR.
  pull_request:

jobs:
  dotnet_build:
    uses: ./.github/workflows/build_dotnet.yml
