name: Provision Azure resources

on: 
  # Allow to be called from other workflows.
  workflow_call:

  # Allow triggering manually. 
  workflow_dispatch:
  
  push:
    branches:
      - main

permissions:
    id-token: write
    contents: read

jobs:
    provision-azure:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout repository
          uses: actions/checkout@main

        - name: Azure authentication
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        # - name: Provision Azure resources
        #   uses: azure/bicep-deploy@v1
        #   with:
        #     type: deployment
        #     operation: create
        #     name: 'AspireLearningInfraDeployment-${{ github.run_id }}'
        #     location: eastus
        #     scope: subscription
        #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #     template-file: ./infra/main.bicep
        #     parameters: '{"environmentName": "${{vars.ENVIRONMENT_NAME}}", "location": "eastus"}'

        - id: bicep-deploy
          name: "Bicep deployment - Provision Azure resources"
          uses: azure/arm-deploy@v2
          with:
            deploymentName: 'AspireLearningInfraDeployment-${{ github.run_id }}'
            scope: subscription
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            region: eastus
            template: ./infra/main.bicep
            parameters: environmentName=${{vars.ENVIRONMENT_NAME}} location=eastus

        - run: echo ${{ steps.bicep-deploy.outputs.outputs }}

        - name: Azure CLI logout
          run: az logout